### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by spuder** [petems/puppet-doc-lint#12]
When I try and use puppet-doc-lint it crashes with one of two errors. 

    undefined method 'tr'
    undefined method 'items'

Running ruby 2.0, installed via rvm on osx

```
sowen@Spencers-MacBook-Pro:~/Code/geppetto/puppet-gitlab/manifests$ puppet-doc-lint init.pp 
/Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/parser.rb:52:in `block (2 levels) in docs': undefined method `tr' for ["*puppet_manage_config*"]:Array (NoMethodError)
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/parser.rb:47:in `each'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/parser.rb:47:in `block in docs'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/parser.rb:45:in `each'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/parser.rb:45:in `docs'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/runner.rb:12:in `block in run'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/runner.rb:5:in `each'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/runner.rb:5:in `run'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/bin/puppet-doc-lint:15:in `<top (required)>'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/puppet-doc-lint:23:in `load'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/puppet-doc-lint:23:in `<main>'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 14:48:45
sowen@Spencers-MacBook-Pro:~/Code/geppetto/puppet-gitlab/manifests$ puppet-doc-lint install.pp 
/Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/parser.rb:70:in `block in authors': undefined method `items' for #<RDoc::Markup::Paragraph:0x007f9ba3672938> (NoMethodError)
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/parser.rb:68:in `each'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/parser.rb:68:in `authors'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/runner.rb:12:in `block in run'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/runner.rb:5:in `each'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/lib/puppet-doc-lint/runner.rb:5:in `run'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/puppet-doc-lint-0.1.1/bin/puppet-doc-lint:15:in `<top (required)>'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/puppet-doc-lint:23:in `load'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/puppet-doc-lint:23:in `<main>'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

Is this not compatible with RVM, or ruby 2.0.0 ?

**Comment by petems** [comment]
Yeah, this is actually a live issue: basically the gem assumes you've formatted your manifests in a particular way, I'm going to add a massive `begin..rescue` around the logic to say "Hey, we make these assumptions" and see if I can improve the logic to make it a bit more generous with how people have formatted their manfests.

**Comment by petems** [comment]
Ok, I think #16 and #15 might fix this, but I think also the version of RDoc required might need changing...
